name: frames_app
description: Frames - Discover Liverpool's Hidden Artists

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # Map
  google_maps_flutter: ^2.9.0

  # QR Scanner
  mobile_scanner: ^7.0.0

  # Location
  geolocator: ^13.0.1

  # Images
  cached_network_image: ^3.4.1

  # Sharing
  share_plus: ^10.1.2

   # Fonts
  google_fonts: ^6.2.1


  # Utils
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/doors/