// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqwgN3WuHrB_D5PaIJmHIXvwQQRbiLEq0',
    appId: '1:684906061756:web:a125ab148b1037d42155b9',
    messagingSenderId: '684906061756',
    projectId: 'frames-app-30d21',
    authDomain: 'frames-app-30d21.firebaseapp.com',
    storageBucket: 'frames-app-30d21.firebasestorage.app',
    measurementId: 'G-LD3TY6ZFXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl38EWtkiBBslboaQUV-tLXtTs6HiRt4A',
    appId: '1:684906061756:android:447caacfb8cad4af2155b9',
    messagingSenderId: '684906061756',
    projectId: 'frames-app-30d21',
    storageBucket: 'frames-app-30d21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jQWIlXALCyXdxJ42mL6engaNEx1fsbg',
    appId: '1:684906061756:ios:f88451a86a0647862155b9',
    messagingSenderId: '684906061756',
    projectId: 'frames-app-30d21',
    storageBucket: 'frames-app-30d21.firebasestorage.app',
    iosBundleId: 'com.example.framesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jQWIlXALCyXdxJ42mL6engaNEx1fsbg',
    appId: '1:684906061756:ios:f88451a86a0647862155b9',
    messagingSenderId: '684906061756',
    projectId: 'frames-app-30d21',
    storageBucket: 'frames-app-30d21.firebasestorage.app',
    iosBundleId: 'com.example.framesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqwgN3WuHrB_D5PaIJmHIXvwQQRbiLEq0',
    appId: '1:684906061756:web:c8d39b44d4c8e1482155b9',
    messagingSenderId: '684906061756',
    projectId: 'frames-app-30d21',
    authDomain: 'frames-app-30d21.firebaseapp.com',
    storageBucket: 'frames-app-30d21.firebasestorage.app',
    measurementId: 'G-64676EZKGD',
  );
}
